namespace ElasticsearchCRUD.Model.SearchModel.Aggregations
{
	/// <summary>
	/// A single-value metrics aggregation that keeps track and returns the minimum value among numeric values extracted from the aggregated documents. 
	/// These values can be extracted either from specific numeric fields in the documents, or be generated by a provided script.
	/// </summary>
	public class MinAggregation : BaseAggregation
	{
		public MinAggregation(string name, string field) : base("min", name,field){}

		public override void WriteJson(ElasticsearchCrudJsonWriter elasticsearchCrudJsonWriter)
		{
			base.WriteJsonBase(elasticsearchCrudJsonWriter, WriteValues);
		}

		private void WriteValues(ElasticsearchCrudJsonWriter elasticsearchCrudJsonWriter)
		{
		}
	}
}
